### ISSUE TITLE
Graphql version conflict.

### ISSUE THREAD

**Issue by killakam3084** [andrew-codes/gatsby-plugin-elasticlunr-search-demo#9]
Since Gatsby's transition to v2...the version of Graphql being included w/ the Gatsby module is now conflicting w/ the version specified in the elasticlunr plugin's dependencies...

May want to consider bumping...

> error gatsby-node.js returned an error
> 
> 
>   Error: Cannot use GraphQLScalarType "SiteSearchIndex_Index" from another module or realm.
>   Ensure that there is only one instance of "graphql" in the node_modules
>   directory. If different versions of "graphql" are the dependencies of other
>   relied on modules, use "resolutions" to ensure only one version is installed.
>   https://yarnpkg.com/en/docs/selective-version-resolutions
>   Duplicate "graphql" modules cannot be used at the same time since different
>   versions may have different capabilities and behavior. The data from one
>   version used in the function from another could produce confusing and
>   spurious results.

**Comment by wozniaklukasz** [comment]
+1

**Comment by wozniaklg** [comment]
I found solution. [Here is similar problem.](https://github.com/gatsbyjs/gatsby/issues/8238#issuecomment-422285937)

After that i removed `yarn.lock` and i had to install `lodash.camelcase`.
